from dataclasses import dataclass
from typing import List, Optional, Dict, Any
import numpy as np
from src.pose.pose import Pose

@dataclass
class FaceData:
    """
    Structured data for storing a single face
    """
    bbox: Optional[List[int]] = None
    embedding: Optional[np.ndarray] = None
    confidence: Optional[float] = None

    # Metadata
    name: Optional[str] = None
    shot_type: Optional[str] = None
    pose: Optional[Pose] = None

    # Numeric Metrics (None = Calculation Failed / Not Run)
    blur_score: Optional[float] = None
    brightness: Optional[float] = None
    yaw: Optional[float] = None
    pitch: Optional[float] = None
    roll: Optional[float] = None

    @property
    def metrics(self) -> Dict[str, Any]:
        data = {}
        # Block specific non-metric fields
        NON_METRIC_FIELDS = {"bbox", "embedding", "name"}

        for key, value in vars(self).items():
            if key.startswith("_") or key in NON_METRIC_FIELDS:
                continue

            data[key] = value

        # Computed metrics
        if self.bbox and len(self.bbox) == 4:
            data["face_height_px"] = self.bbox[3] - self.bbox[1]
            data["face_width_px"] = self.bbox[2] - self.bbox[0]

        return data

@dataclass
class ImageAnalysisResult:
    """
    The complete AI analysis of a photo
    """
    # Essential keys (always loaded)
    original_path: Optional[str]
    photo_id: Optional[str]
    display_path: Optional[str]

    # Lazy fields (None until hydrated)
    timestamp: Optional[str] = None
    month: Optional[int] = None
    # Morning, Evening, Night.....
    time_period: Optional[str] = None
    semantic_vector: Optional[np.ndarray] = None
    original_width: Optional[int] = None
    original_height: Optional[int] = None
    aesthetic_score: Optional[float] = None
    iso: Optional[int] = None
    global_blur: Optional[float] = None
    global_brightness: Optional[float] = None
    global_contrast: Optional[float] = None

    # Caption generated by Vision -> Embeddings
    caption: str = ""
    caption_vector: Optional[List[float]] = None

    # Complex nested data
    faces: Optional[List[FaceData]] = None

    @property
    def metrics(self) -> Dict[str, Any]:
        data = {}
        NON_METRIC_FIELDS = {
            "photo_id", "original_path", "display_path", "file_hash",
            "faces", "semantic_vector", "meta_tags", "original_width", "original_height"
        }

        for key, value in vars(self).items():
            if key.startswith("_") or key in NON_METRIC_FIELDS: continue

            data[key] = value

        return data