from dataclasses import dataclass
from typing import List, Optional
import numpy as np
from src.pose.pose import Pose

@dataclass
class FaceData:
    """
    Structured data for storing a single face.

    For UI display, use extract_face_display_values() from src.features.registry.
    For metrics tracking, use IngestionMetricsTracker with the feature registry.
    """
    bbox: Optional[List[int]] = None
    embedding: Optional[np.ndarray] = None
    confidence: Optional[float] = None

    # Metadata
    name: Optional[str] = None
    shot_type: Optional[str] = None
    pose: Optional[Pose] = None

    # Numeric Metrics (None = Calculation Failed / Not Run)
    blur_score: Optional[float] = None
    brightness: Optional[float] = None
    yaw: Optional[float] = None
    pitch: Optional[float] = None
    roll: Optional[float] = None


@dataclass
class ImageAnalysisResult:
    """
    The complete AI analysis of a photo.

    For UI display, use extract_ui_display_values() from src.features.registry.
    For metrics tracking, use IngestionMetricsTracker with the feature registry.
    """
    # Essential keys (always loaded)
    original_path: Optional[str]
    photo_id: Optional[str]
    display_path: Optional[str]

    # Lazy fields (None until hydrated)
    timestamp: Optional[str] = None
    month: Optional[int] = None
    # Morning, Evening, Night.....
    time_period: Optional[str] = None
    semantic_vector: Optional[np.ndarray] = None
    original_width: Optional[int] = None
    original_height: Optional[int] = None
    aesthetic_score: Optional[float] = None
    iso: Optional[int] = None
    global_blur: Optional[float] = None
    global_brightness: Optional[float] = None
    global_contrast: Optional[float] = None

    # Caption generated by Vision -> Embeddings
    caption: str = ""
    caption_vector: Optional[List[float]] = None

    # Complex nested data
    faces: Optional[List[FaceData]] = None